name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_BM_KEY }}'

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: _json_key
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.GCP_SA_BM_KEY }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: eu.gcr.io
          # Docker repository to tag the image with
          repository: ${{ secrets.GOOGLE_PROJECT_ID }}/tejathota
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Automatically tags the built image with the git short SHA as per the readme
          tag_with_sha: true
          # Comma-delimited list of labels to add to the built image
          labels: github-action-build
          # Whether to push the image
          push: true


      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'tejabeta-cloud-run-service'
          image: 'eu.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/tejathota:latest'
          region: '${{ secrets.REGION }}'
